---
kind: pipeline
type: docker
name: default-build

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: build
    image: golang:1.14.2
    commands:
      - apt-get update && apt-get install -y cmake
      - make test
      - make build
  - name: lint
    image: golangci/golangci-lint
    custom_dns: 8.8.8.8
    commands:
      - chmod 666 go.sum
      - golangci-lint run -v
  - name: test
    image: golang:1.14.2
    commands:
      - ./contrib/go-test.sh
  - name: coverage
    image: plugins/codecov
    settings:
      required: true
      token:
        from_secret: codecov-token
    when:
      event:
        - push
      # branch: master
  - name: publish-test
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event:
        - push
      branch: ibc
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile
      repo: publicawesome/stakebird
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
  - name: deploy-devnet
    image: appleboy/drone-scp
    settings:
      username: ubuntu
      host:
        from_secret: devnet_host
      key:
        from_secret: deploy_key
      target:
        from_secret: deploy_home
      source:
        - bin/
    when:
      event:
        - push
      branch: master
  - name: deploy-devnet-srv
    image: appleboy/drone-ssh
    settings:
      username: ubuntu
      host:
        from_secret: devnet_host
      key:
        from_secret: deploy_key
      target:
        from_secret: deploy_home
      script:
        - sh ~/deploy-devnet.sh
    when:
      event:
        - push
      branch: master

  - name: release
    image: golang:1.14.2
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event:
        - tag
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: ibc-integration-test

steps:
  - name: gaiad
    image: golang:1.14.2
    detach: true
    commands:
      - ./contrib/ci/setup-gaia.sh
  - name: stakebird
    image: golang:1.14.2
    commands:
      - ./contrib/ci/setup-stakebird.sh
    detach: true
  - name: relayer
    image: golang:1.14.2
    commands:
      - /bin/bash ./contrib/ci/setup-relayer.sh
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - default-build
---
kind: signature
hmac: 6b09abab578013ded88bc823cc45261a44b5a61515ce2d5b4c79e376c69f6f32
