---
kind: pipeline
type: docker
name: default-build

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: lint
    image: golangci/golangci-lint:v1.31
    commands:
      - export GL_DEBUG=linters_output
      - export GOPACKAGESPRINTGOLISTERRORS=1
      - go mod download
      - golangci-lint run -v --timeout 5m --tests=false
    environment:
      GOPROXY: http://goproxy
  - name: test-and-build
    image: golang:1.15.2
    commands:
      - apt-get update && apt-get install -y cmake
      - ./contrib/go-test.sh
      - make build-linux
    environment:
      GOPROXY: http://goproxy
  - name: coverage
    image: plugins/codecov
    settings:
      required: true
      token:
        from_secret: codecov-token
    when:
      event:
        - push
        - pull_request
  - name: publish-test
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event:
        - push
      branch: ibc
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile
      repo: publicawesome/stakebird
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
  - name: trigger
    image: plugins/downstream
    settings:
      server:
        from_secret: ci_server
      token:
        from_secret: ci_token
      fork: true
      repositories:
        from_secret: downstream_repositories
    when:
      branch: master
      event:
        - push
  - name: release
    image: golang:1.15.2
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - curl -sL https://git.io/goreleaser | bash
    environment:
      GOPROXY: http://goproxy
    when:
      event:
        - tag
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: discord_webhook_id
      webhook_token: 
        from_secret: discord_webhook_token
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: ibc-integration-test

steps:
  - name: gaiad
    image: golang:1.15.2
    detach: true
    commands:
      - ./contrib/ci/setup-gaia.sh
    environment:
      GOPROXY: http://goproxy
  - name: stakebird
    image: golang:1.15.2
    commands:
      - ./contrib/ci/setup-stakebird.sh
    environment:
      GOPROXY: http://goproxy
    detach: true
  - name: relayer
    image: golang:1.15.2
    commands:
      - /bin/bash ./contrib/ci/setup-relayer.sh
    environment:
      GOPROXY: http://goproxy
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - default-build
---
kind: signature
hmac: 085a3bf1bdd946ccf674af77a5109c91e451afa7d5f5d1d3a38dd4902c58b14c

...
