---
kind: pipeline
type: docker
name: default-build

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
  - name: lint
    image: golangci/golangci-lint:v1.31
    commands:
      - export GL_DEBUG=linters_output
      - export GOPACKAGESPRINTGOLISTERRORS=1
      - go mod download
      - golangci-lint run -v --timeout 5m --tests=false --skip-dirs="simapp"
    environment:
      GOPROXY: http://goproxy
  - name: test-and-build
    image: golang:1.15.2
    commands:
      - apt-get update && apt-get install -y cmake
      - ./contrib/go-test.sh
      - FAUCET_ENABLED=true make build-linux
      - make build-linux
    environment:
      GOPROXY: http://goproxy
  - name: coverage
    image: plugins/codecov
    settings:
      required: true
      token:
        from_secret: codecov-token
    when:
      event:
        - push
        - pull_request
  - name: publish-test
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile.test
      repo: rocketprotocol/rocketzone-relayer-test
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
    when:
      event:
        - push
      branch: ibc
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: docker/Dockerfile
      repo: publicawesome/stakebird
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - develop
    when:
      event:
        - push
      branch:
        - develop
  - name: trigger
    image: plugins/downstream
    settings:
      server:
        from_secret: ci_server
      token:
        from_secret: ci_token
      fork: true
      repositories:
        from_secret: downstream_repositories
    when:
      branch: master
      event:
        - push
  - name: release
    image: golang:1.15.2
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - curl -sL https://git.io/goreleaser | bash
    environment:
      GOPROXY: http://goproxy
    when:
      event:
        - tag
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: discord_webhook_id
      webhook_token: 
        from_secret: discord_webhook_token
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: ibc-integration-test

steps:
  - name: gaiad
    image: golang:1.15.2
    detach: true
    commands:
      - ./contrib/ci/setup-gaia.sh
    environment:
      GOPROXY: http://goproxy
  - name: stakebird
    image: golang:1.15.2
    commands:
      - ./contrib/ci/setup-stakebird.sh
    environment:
      GOPROXY: http://goproxy
    detach: true
  - name: relayer
    image: golang:1.15.2
    commands:
      - /bin/bash ./contrib/ci/setup-relayer.sh
    environment:
      GOPROXY: http://goproxy

trigger:
  branch:
    - ibc
  event:
    - push

depends_on:
  - default-build
---
kind: signature
hmac: a5f45b999cce3a0055841897214bd1de4c2c5cb3d0ece33360f3462f81257181

...
