before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/staked/
    id: 'staked'
    binary: staked
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=netgo,faucet
    ldflags:
      - -X "github.com/cosmos/cosmos-sdk/version.Name=Stargaze"
      - -X github.com/cosmos/cosmos-sdk/version.AppName=staked
      - -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,faucet

release:
  github:
    owner: public-awesome
    name: stargaze
  draft: true
  prerelease: auto

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  skip: true
